export default{
    BOTTOM: 'Bottom',
    HEADER: 'Header',
    SETTING: 'Setting',
    STREAM : 'Stream',
    MOVIES: 'Movies',
    DOWNLOADSETTING: 'DownloadSet',
    HOMETAB: 'Home',
    CHANNEL: 'Channel',
    FIND : "Find",
    DOWNLOADS: "Downoads",
    MY_STUFF: "My Stuff",
    LOGIN: "LogIn",
    SIGNUP:"SignUp",
    HOME: 'Home',
    TVSHOWS: 'TVShows',
    TOP_MOVIES: 'Movies',
    KIDS: 'Kids',
}